import os
import shutil
import sys

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import builder

# --- BOOK METADATA ---
BOOK_TITLE = "Embedded Modular Development"
BOOK_AUTHOR = "Miguel Esparza"

# --- CONFIGURATION ---
ROOT_DIR = os.getcwd()
SOURCE_DIR = os.path.join(ROOT_DIR, "book")
BUILD_DIR = os.path.join(ROOT_DIR, "build")
STRUCTURE_FILE = os.path.join(SOURCE_DIR, "structure.txt")

def ensure_build_dir():
    # Create build dir if it doesn't exist, but DO NOT delete it if it does.
    if not os.path.exists(BUILD_DIR):
        os.makedirs(BUILD_DIR)

def get_structure():
    """
    Parses structure.txt. Returns a list of dicts:
    [{'file': 'ch1.md', 'is_section': False}, {'file': 'ch1_1.md', 'is_section': True}]
    """
    if not os.path.exists(STRUCTURE_FILE):
        print("[WARNING] structure.txt not found. Scanning directory alphabetically.")
        return [{'file': f, 'is_section': False} for f in sorted(os.listdir(SOURCE_DIR)) 
                if f.endswith(".md") and not f.startswith("_")]

    items = []
    with open(STRUCTURE_FILE, 'r', encoding='utf-8') as f:
        for line in f:
            raw_line = line.rstrip()
            stripped = raw_line.strip()
            
            if not stripped or stripped.startswith('#'):
                continue
            
            # Detect indentation (start with whitespace)
            is_section = raw_line.startswith(' ') or raw_line.startswith('\t')
            
            if os.path.exists(os.path.join(SOURCE_DIR, stripped)):
                items.append({'file': stripped, 'is_section': is_section})
            else:
                print(f"[WARNING] Missing file: {stripped}")
    return items

def generate_typst_master(structure_items):
    typst_path = os.path.join(BUILD_DIR, "main.typ")
    
    with open(typst_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by build_book.py\n')
        f.write('#import "@preview/cmarker:0.1.8"\n')
        
        # IMPORT 'draft' and 'convention' HERE:
        f.write('#import "../book/template.typ": project, draft, convention\n\n') 
        
        f.write(f'#show: project.with(\n')
        f.write(f'  title: "{BOOK_TITLE}",\n')
        f.write(f'  authors: ("{BOOK_AUTHOR}",),\n')
        f.write(f')\n\n')

        first_chapter = True
        for item in structure_items:
            filename = item['file']
            is_section = item['is_section']
            
            f.write(f'// --- {filename} ---\n')
            if not is_section:
                if not first_chapter:
                    f.write('#pagebreak(weak: true)\n')
                first_chapter = False

            # PASS SCOPE AND HTML OVERRIDES HERE:
            f.write(
                f'#cmarker.render(read("{filename}"), '
                'html: (\n'
                '  convention: ("normal", (attrs, body) => convention(id: attrs.id, title: attrs.title, body)),\n'
                '  draft: ("normal", (attrs, body) => draft(body)),\n'
                '),\n'
                'scope: (draft: draft, convention: convention))\n\n'
            )
            
    return typst_path

def main():
    print("--- C Book Builder ---")
    try:
        ensure_build_dir()
        
        # 1. Read Structure
        structure_items = get_structure()
        if not structure_items:
            print("[ERROR] No chapters found.")
            sys.exit(1)

        print(f"[1/2] Processing {len(structure_items)} files...")
        
        # 2. Process Markdown
        for item in structure_items:
            chap = item['file']
            in_path = os.path.join(SOURCE_DIR, chap)
            out_path = os.path.join(BUILD_DIR, chap)
            
            with open(in_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            try:
                new_content = builder.process_markdown_content(content, ROOT_DIR)
                with open(out_path, 'w', encoding='utf-8') as f:
                    f.write(new_content)
            except Exception as e:
                print(f"\n[ERROR] Failed in {chap}: {e}")
                sys.exit(1)

        # 3. Generate Typst
        print("\n[2/2] Generating Typst wrapper...")
        generate_typst_master(structure_items)
        print("--- Build Complete ---")

    except Exception as e:
        print(f"Fatal Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
